AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  MentalHealthFlashBriefing:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::556604628648:role/service-role/Test1a'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MentalHealthFlashBriefing
            Method: ANY
